version: '3.9'

services:
  app:
    container_name: todo-list
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8080:80"
    build: .

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - .db/sql:/sql
      - .db/var:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network: 
  
